name: verify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: setup-python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.10' 

    - id: install-dependencies
      run: pip3 install -U online-judge-verify-helper

    - id: run-tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify all
      working-directory: ./verify